const moment = require("moment");
const { v4: uuidv4 } = require("uuid");
const short = require("short-uuid");
const fs = require("fs");

const data = [
  {
    sno: 2,
    "start-time": "00:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0015AM",
    slot: "OPEN",
    "open-draw-time": "00:15",
    "close-draw-time": "00:30",
  },
  {
    sno: 3,
    "start-time": "00:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0030AM",
    slot: "OPEN",
    "open-draw-time": "00:30",
    "close-draw-time": "00:45",
  },
  {
    sno: 4,
    "start-time": "00:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0045AM",
    slot: "OPEN",
    "open-draw-time": "00:45",
    "close-draw-time": "01:00",
  },
  {
    sno: 5,
    "start-time": "01:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0100AM",
    slot: "OPEN",
    "open-draw-time": "01:00",
    "close-draw-time": "01:15",
  },
  {
    sno: 6,
    "start-time": "01:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0115AM",
    slot: "OPEN",
    "open-draw-time": "01:15",
    "close-draw-time": "01:30",
  },
  {
    sno: 7,
    "start-time": "01:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0130AM",
    slot: "OPEN",
    "open-draw-time": "01:30",
    "close-draw-time": "01:45",
  },
  {
    sno: 8,
    "start-time": "01:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0145AM",
    slot: "OPEN",
    "open-draw-time": "01:45",
    "close-draw-time": "02:00",
  },
  {
    sno: 9,
    "start-time": "02:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ200AM",
    slot: "OPEN",
    "open-draw-time": "02:00",
    "close-draw-time": "02:15",
  },
  {
    sno: 10,
    "start-time": "02:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0215AM",
    slot: "OPEN",
    "open-draw-time": "02:15",
    "close-draw-time": "02:30",
  },
  {
    sno: 11,
    "start-time": "02:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0230AM",
    slot: "OPEN",
    "open-draw-time": "02:30",
    "close-draw-time": "02:45",
  },
  {
    sno: 12,
    "start-time": "02:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0245AM",
    slot: "OPEN",
    "open-draw-time": "02:45",
    "close-draw-time": "03:00",
  },
  {
    sno: 13,
    "start-time": "03:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0300AM",
    slot: "OPEN",
    "open-draw-time": "03:00",
    "close-draw-time": "03:15",
  },
  {
    sno: 14,
    "start-time": "03:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0315AM",
    slot: "OPEN",
    "open-draw-time": "03:15",
    "close-draw-time": "03:30",
  },
  {
    sno: 15,
    "start-time": "03:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0330AM",
    slot: "OPEN",
    "open-draw-time": "03:30",
    "close-draw-time": "03:45",
  },
  {
    sno: 16,
    "start-time": "03:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0345AM",
    slot: "OPEN",
    "open-draw-time": "03:45",
    "close-draw-time": "04:00",
  },
  {
    sno: 17,
    "start-time": "04:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ400AM",
    slot: "OPEN",
    "open-draw-time": "04:00",
    "close-draw-time": "04:15",
  },
  {
    sno: 18,
    "start-time": "04:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0415AM",
    slot: "OPEN",
    "open-draw-time": "04:15",
    "close-draw-time": "04:30",
  },
  {
    sno: 19,
    "start-time": "04:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0430AM",
    slot: "OPEN",
    "open-draw-time": "04:30",
    "close-draw-time": "04:45",
  },
  {
    sno: 20,
    "start-time": "04:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0445AM",
    slot: "OPEN",
    "open-draw-time": "04:45",
    "close-draw-time": "05:00",
  },
  {
    sno: 21,
    "start-time": "05:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0500AM",
    slot: "OPEN",
    "open-draw-time": "05:00",
    "close-draw-time": "05:15",
  },
  {
    sno: 22,
    "start-time": "05:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0515AM",
    slot: "OPEN",
    "open-draw-time": "05:15",
    "close-draw-time": "05:30",
  },
  {
    sno: 23,
    "start-time": "05:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0530AM",
    slot: "OPEN",
    "open-draw-time": "05:30",
    "close-draw-time": "05:45",
  },
  {
    sno: 24,
    "start-time": "05:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0545AM",
    slot: "OPEN",
    "open-draw-time": "05:45",
    "close-draw-time": "06:00",
  },
  {
    sno: 25,
    "start-time": "06:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ600AM",
    slot: "OPEN",
    "open-draw-time": "06:00",
    "close-draw-time": "06:15",
  },
  {
    sno: 26,
    "start-time": "06:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0615AM",
    slot: "OPEN",
    "open-draw-time": "06:15",
    "close-draw-time": "06:30",
  },
  {
    sno: 27,
    "start-time": "06:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0630AM",
    slot: "OPEN",
    "open-draw-time": "06:30",
    "close-draw-time": "06:45",
  },
  {
    sno: 28,
    "start-time": "06:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0645AM",
    slot: "OPEN",
    "open-draw-time": "06:45",
    "close-draw-time": "07:00",
  },
  {
    sno: 29,
    "start-time": "07:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0700AM",
    slot: "OPEN",
    "open-draw-time": "07:00",
    "close-draw-time": "07:15",
  },
  {
    sno: 30,
    "start-time": "07:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0715AM",
    slot: "OPEN",
    "open-draw-time": "07:15",
    "close-draw-time": "07:30",
  },
  {
    sno: 31,
    "start-time": "07:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0730AM",
    slot: "OPEN",
    "open-draw-time": "07:30",
    "close-draw-time": "07:45",
  },
  {
    sno: 32,
    "start-time": "07:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0745AM",
    slot: "OPEN",
    "open-draw-time": "07:45",
    "close-draw-time": "08:00",
  },
  {
    sno: 33,
    "start-time": "08:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ800AM",
    slot: "OPEN",
    "open-draw-time": "08:00",
    "close-draw-time": "08:15",
  },
  {
    sno: 34,
    "start-time": "08:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0815AM",
    slot: "OPEN",
    "open-draw-time": "08:15",
    "close-draw-time": "08:30",
  },
  {
    sno: 35,
    "start-time": "08:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0830AM",
    slot: "OPEN",
    "open-draw-time": "08:30",
    "close-draw-time": "08:45",
  },
  {
    sno: 36,
    "start-time": "08:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0845AM",
    slot: "OPEN",
    "open-draw-time": "08:45",
    "close-draw-time": "09:00",
  },
  {
    sno: 37,
    "start-time": "09:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT900AM",
    slot: "OPEN",
    "open-draw-time": "09:00",
    "close-draw-time": "09:15",
  },
  {
    sno: 38,
    "start-time": "09:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT915AM",
    slot: "OPEN",
    "open-draw-time": "09:15",
    "close-draw-time": "09:30",
  },
  {
    sno: 39,
    "start-time": "09:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM930AM",
    slot: "OPEN",
    "open-draw-time": "09:30",
    "close-draw-time": "09:45",
  },
  {
    sno: 40,
    "start-time": "09:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ945AM",
    slot: "OPEN",
    "open-draw-time": "09:45",
    "close-draw-time": "10:00",
  },
  {
    sno: 41,
    "start-time": "10:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ1000AM",
    slot: "OPEN",
    "open-draw-time": "10:00",
    "close-draw-time": "10:15",
  },
  {
    sno: 42,
    "start-time": "10:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN1015AM",
    slot: "OPEN",
    "open-draw-time": "10:15",
    "close-draw-time": "10:30",
  },
  {
    sno: 43,
    "start-time": "10:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB1030AM",
    slot: "OPEN",
    "open-draw-time": "10:30",
    "close-draw-time": "10:45",
  },
  {
    sno: 44,
    "start-time": "10:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL1045AM",
    slot: "OPEN",
    "open-draw-time": "10:45",
    "close-draw-time": "11:00",
  },
  {
    sno: 45,
    "start-time": "11:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT1100AM",
    slot: "OPEN",
    "open-draw-time": "11:00",
    "close-draw-time": "11:15",
  },
  {
    sno: 46,
    "start-time": "11:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT1115AM",
    slot: "OPEN",
    "open-draw-time": "11:15",
    "close-draw-time": "11:30",
  },
  {
    sno: 47,
    "start-time": "11:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM1130AM",
    slot: "OPEN",
    "open-draw-time": "11:30",
    "close-draw-time": "11:45",
  },
  {
    sno: 48,
    "start-time": "11:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ1145AM",
    slot: "OPEN",
    "open-draw-time": "11:45",
    "close-draw-time": "12:00",
  },
  {
    sno: 49,
    "start-time": "12:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ1200PM",
    slot: "OPEN",
    "open-draw-time": "12:00",
    "close-draw-time": "12:15",
  },
  {
    sno: 50,
    "start-time": "12:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN1215PM",
    slot: "OPEN",
    "open-draw-time": "12:15",
    "close-draw-time": "12:30",
  },
  {
    sno: 51,
    "start-time": "12:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB1230PM",
    slot: "OPEN",
    "open-draw-time": "12:30",
    "close-draw-time": "12:45",
  },
  {
    sno: 52,
    "start-time": "12:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL1245PM",
    slot: "OPEN",
    "open-draw-time": "12:45",
    "close-draw-time": "13:00",
  },
  {
    sno: 53,
    "start-time": "13:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0100PM",
    slot: "OPEN",
    "open-draw-time": "13:00",
    "close-draw-time": "13:15",
  },
  {
    sno: 54,
    "start-time": "13:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0115PM",
    slot: "OPEN",
    "open-draw-time": "13:15",
    "close-draw-time": "13:30",
  },
  {
    sno: 55,
    "start-time": "13:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0130PM",
    slot: "OPEN",
    "open-draw-time": "13:30",
    "close-draw-time": "13:45",
  },
  {
    sno: 56,
    "start-time": "13:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0145PM",
    slot: "OPEN",
    "open-draw-time": "13:45",
    "close-draw-time": "14:00",
  },
  {
    sno: 57,
    "start-time": "14:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ200PM",
    slot: "OPEN",
    "open-draw-time": "14:00",
    "close-draw-time": "14:15",
  },
  {
    sno: 58,
    "start-time": "14:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0215PM",
    slot: "OPEN",
    "open-draw-time": "14:15",
    "close-draw-time": "14:30",
  },
  {
    sno: 59,
    "start-time": "14:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0230PM",
    slot: "OPEN",
    "open-draw-time": "14:30",
    "close-draw-time": "14:45",
  },
  {
    sno: 60,
    "start-time": "14:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0245PM",
    slot: "OPEN",
    "open-draw-time": "14:45",
    "close-draw-time": "15:00",
  },
  {
    sno: 61,
    "start-time": "15:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0300PM",
    slot: "OPEN",
    "open-draw-time": "15:00",
    "close-draw-time": "15:15",
  },
  {
    sno: 62,
    "start-time": "15:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0315PM",
    slot: "OPEN",
    "open-draw-time": "15:15",
    "close-draw-time": "15:30",
  },
  {
    sno: 63,
    "start-time": "15:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0330PM",
    slot: "OPEN",
    "open-draw-time": "15:30",
    "close-draw-time": "15:45",
  },
  {
    sno: 64,
    "start-time": "15:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0345PM",
    slot: "OPEN",
    "open-draw-time": "15:45",
    "close-draw-time": "16:00",
  },
  {
    sno: 65,
    "start-time": "16:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ400PM",
    slot: "OPEN",
    "open-draw-time": "16:00",
    "close-draw-time": "16:15",
  },
  {
    sno: 66,
    "start-time": "16:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0415PM",
    slot: "OPEN",
    "open-draw-time": "16:15",
    "close-draw-time": "16:30",
  },
  {
    sno: 67,
    "start-time": "16:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0430PM",
    slot: "OPEN",
    "open-draw-time": "16:30",
    "close-draw-time": "16:45",
  },
  {
    sno: 68,
    "start-time": "16:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0445PM",
    slot: "OPEN",
    "open-draw-time": "16:45",
    "close-draw-time": "17:00",
  },
  {
    sno: 69,
    "start-time": "17:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0500PM",
    slot: "OPEN",
    "open-draw-time": "17:00",
    "close-draw-time": "17:15",
  },
  {
    sno: 70,
    "start-time": "17:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0515PM",
    slot: "OPEN",
    "open-draw-time": "17:15",
    "close-draw-time": "17:30",
  },
  {
    sno: 71,
    "start-time": "17:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0530PM",
    slot: "OPEN",
    "open-draw-time": "17:30",
    "close-draw-time": "17:45",
  },
  {
    sno: 72,
    "start-time": "17:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0545PM",
    slot: "OPEN",
    "open-draw-time": "17:45",
    "close-draw-time": "18:00",
  },
  {
    sno: 73,
    "start-time": "18:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ600PM",
    slot: "OPEN",
    "open-draw-time": "18:00",
    "close-draw-time": "18:15",
  },
  {
    sno: 74,
    "start-time": "18:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0615PM",
    slot: "OPEN",
    "open-draw-time": "18:15",
    "close-draw-time": "18:30",
  },
  {
    sno: 75,
    "start-time": "18:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0630PM",
    slot: "OPEN",
    "open-draw-time": "18:30",
    "close-draw-time": "18:45",
  },
  {
    sno: 76,
    "start-time": "18:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0645PM",
    slot: "OPEN",
    "open-draw-time": "18:45",
    "close-draw-time": "19:00",
  },
  {
    sno: 77,
    "start-time": "19:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0700PM",
    slot: "OPEN",
    "open-draw-time": "19:00",
    "close-draw-time": "19:15",
  },
  {
    sno: 78,
    "start-time": "19:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0715PM",
    slot: "OPEN",
    "open-draw-time": "19:15",
    "close-draw-time": "19:30",
  },
  {
    sno: 79,
    "start-time": "19:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0730PM",
    slot: "OPEN",
    "open-draw-time": "19:30",
    "close-draw-time": "19:45",
  },
  {
    sno: 80,
    "start-time": "19:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0745PM",
    slot: "OPEN",
    "open-draw-time": "19:45",
    "close-draw-time": "20:00",
  },
  {
    sno: 81,
    "start-time": "20:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ800PM",
    slot: "OPEN",
    "open-draw-time": "20:00",
    "close-draw-time": "20:15",
  },
  {
    sno: 82,
    "start-time": "20:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN0815PM",
    slot: "OPEN",
    "open-draw-time": "20:15",
    "close-draw-time": "20:30",
  },
  {
    sno: 83,
    "start-time": "20:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB0830PM",
    slot: "OPEN",
    "open-draw-time": "20:30",
    "close-draw-time": "20:45",
  },
  {
    sno: 84,
    "start-time": "20:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL0845PM",
    slot: "OPEN",
    "open-draw-time": "20:45",
    "close-draw-time": "21:00",
  },
  {
    sno: 85,
    "start-time": "21:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT0900PM",
    slot: "OPEN",
    "open-draw-time": "21:00",
    "close-draw-time": "21:15",
  },
  {
    sno: 86,
    "start-time": "21:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT0915PM",
    slot: "OPEN",
    "open-draw-time": "21:15",
    "close-draw-time": "21:30",
  },
  {
    sno: 87,
    "start-time": "21:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM0930PM",
    slot: "OPEN",
    "open-draw-time": "21:30",
    "close-draw-time": "21:45",
  },
  {
    sno: 88,
    "start-time": "21:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ0945PM",
    slot: "OPEN",
    "open-draw-time": "21:45",
    "close-draw-time": "22:00",
  },
  {
    sno: 89,
    "start-time": "22:00",
    "product-name": "Matka Raaj",
    "product-id": "MRAJ1000PM",
    slot: "OPEN",
    "open-draw-time": "22:00",
    "close-draw-time": "22:15",
  },
  {
    sno: 90,
    "start-time": "22:15",
    "product-name": "Matka Pune",
    "product-id": "MPUN1015PM",
    slot: ["OPEN"],
    "open-draw-time": "22:15",
    "close-draw-time": "22:30",
  },
  {
    sno: 91,
    "start-time": "22:30",
    "product-name": "Matka Mumbai",
    "product-id": "MMUB1030PM",
    slot: "OPEN",
    "open-draw-time": "22:30",
    "close-draw-time": "22:45",
  },
  {
    sno: 92,
    "start-time": "22:45",
    "product-name": "Matka Kalyan",
    "product-id": "MKAL1045PM",
    slot: "OPEN",
    "open-draw-time": "22:45",
    "close-draw-time": "23:00",
  },
  {
    sno: 93,
    "start-time": "23:00",
    "product-name": "Matka Satra",
    "product-id": "MSAT1100PM",
    slot: "OPEN",
    "open-draw-time": "23:00",
    "close-draw-time": "23:15",
  },
  {
    sno: 94,
    "start-time": "23:15",
    "product-name": "Matka Ratan",
    "product-id": "MRAT1115PM",
    slot: "OPEN",
    "open-draw-time": "23:15",
    "close-draw-time": "23:30",
  },
  {
    sno: 95,
    "start-time": "23:30",
    "product-name": "Matka Bombay",
    "product-id": "MBOM1130PM",
    slot: "OPEN",
    "open-draw-time": "23:30",
    "close-draw-time": "23:45",
  },
  {
    sno: 96,
    "start-time": "23:45",
    "product-name": "Matka Bazar",
    "product-id": "MBAZ1145PM",
    slot: "OPEN",
    "open-draw-time": "23:45",
    "close-draw-time": "00:00",
  },
];


let ans = [];

for (let i = 0; i < 365 * 2; i++) {
  console.log("Generating::::::::", i);
  const req = data.map((el) => {
    const ostart = el["open-draw-time"].split(":")[0];
    const oend = el["open-draw-time"].split(":")[1];
    const cstart = el["close-draw-time"].split(":")[0];
    const cend = el["close-draw-time"].split(":")[1];
    const timeToExpire = moment().diff(
      moment({ hours: ostart, minutes: oend, seconds: 00 }).add(i, "d")
    );

    const timeToClose = moment().diff(
      moment({ hours: cstart, minutes: cend, seconds: 00 }).add(i, "d")
    );

    return {
      productName: el["product-name"],
      productId: el["product-id"],
      drawId: uuidv4(),
      shortId: short.generate(),
      date: moment({ hours: 00, minutes: 00, seconds: 00 })
        .add(i, "d")
        .format("DD-MM-YYYY"),
      openDrawTime: moment({ hours: ostart, minutes: oend, seconds: 00 })
        .add(i, "d")
        .unix(),
      closeDrawTime: moment({ hours: cstart, minutes: cend, seconds: 00 })
        .add(i, "d")
        .unix(),
      openNumbers: [],
      closeNumbers: [],
      slot: ["OPEN", "CLOSE"],
      openDrawStatus: timeToExpire < 0 ? "TO_BE_DRAWN" : "DRAW_IN_PROGESS",
      closeDrawStatus: timeToClose < 0 ? "TO_BE_DRAWN" : "DRAW_IN_PROGESS",
      createdAt: moment().unix(),
      updatedAt: moment().unix(),
      createdBy: "SYSTEM",
    };
  });

  ans = [...ans, ...req];
}

fs.writeFileSync("finalData.json", JSON.stringify(ans), "utf-8", (err) => {
  if (err) throw err;
  console.log("Data added to file");
});
